version: 2
config_android:
  docker:
    - image: circleci/android:api-28
  working_directory: ~/project
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx1024m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
    TERM: dumb
jobs:
  build:
    docker:
      - image: circleci/android:api-28

    working_directory: ~/project

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Build test and lint
          command: |
            ./gradlew assembleMockDebug assembleProdDebug assembleMockDebugAndroidTest testMockDebug testProdDebug lintMockDebug lintProdDebug

      - store_test_results:
      path: ~/junit
        - store_artifacts:
            path: ~/junit
            destination: tests
        - store_artifacts:
            path: ./app/build/reports
            destination: reports/

        - persist_to_workspace:
            root: .
            paths:
              - ./app/build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_setup
      - run_ftl:
          requires:
            - build_and_setup